local:
  DEPLOYMENT_BUCKET: 'DEPLOYMENT_BUCKET'
  HYDRATION_CHUNKS_BUCKET: 'hydration-chunks-bucket'
  HYDRATION_MAIN_BUCKET: 'hydration-bucket-main'
  IAM_ROLE: 'IAM_ROLE'
  IAM_ROLE_DEPLOYER: 'IAM_ROLE_DEPLOYER'
  SECURITY_GROUP_ID: 'SECURITY_GROUP_ID'
  SUBNET_ID_1: 'SUBNET_ID_1'
  SUBNET_ID_2: 'SUBNET_ID_2'
  SUBNET_ID_3: 'SUBNET_ID_3'
  SUBNET_ID_4: 'SUBNET_ID_4'
test:
  ALLOWED_ORIGINS: http://localhost:4200
  DEPLOYMENT_BUCKET: 'hydration-deployment-bucket'
  DB_INSTANCE_CLASS: 'db.t3.medium'
  DB_MASTER_USERNAME: 'brillioDevs'
  DB_MASTER_PASSWORD: 'brillioDevs12345'
  HYDRATION_CHUNKS_BUCKET: 'hydration-chunks-bucket'
  HYDRATION_CLUSTER: 'hydration-cluster'
  HYDRATION_CLUSTER_PARAMETER_GROUP: 'hydration-cluster-parameter-group'
  HYDRATION_INSTANCE: 'hydration-instance'
  HYDRATION_MAIN_BUCKET: 'hydration-bucket-main'
  HYDRATION_QUEUE: 'hydration-queue'
  HYDRATION_STATE_MACHINE: 'hydration-state-machine'
  HYDRATION_TABLE: 'hydration-test-records'
  SIGNED_URL_TEST_BUCKET: 'multipart-upload-s3-test'
  API_VERSION: '2006-03-01'
  SECURITY_GROUP_ID: 'sg-042f034199dae1f16'
  SUBNET_ID_1: 'subnet-096cb33e8bdc8609d'
  SUBNET_ID_2: 'subnet-0500c6c07ed1d3634'
  SUBNET_ID_3: 'subnet-0cba6b273a155d68a'
  SUBNET_ID_4: 'subnet-0db1ab78cbc425f5d'
prod:
  DEPLOYMENT_BUCKET: 'DEPLOYMENT_BUCKET'
  HYDRATION_CHUNKS_BUCKET: 'hydration-chunks-bucket'
  HYDRATION_MAIN_BUCKET: 'hydration-bucket-main'
  IAM_ROLE: 'IAM_ROLE'
  IAM_ROLE_DEPLOYER: 'IAM_ROLE_DEPLOYER'
  SECURITY_GROUP_ID: 'SECURITY_GROUP_ID'
  SUBNET_ID_1: 'SUBNET_ID_1'
  SUBNET_ID_2: 'SUBNET_ID_2'
  SUBNET_ID_3: 'SUBNET_ID_3'
  SUBNET_ID_4: 'SUBNET_ID_4'
